name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ENV: test

jobs:
  check:
    name: Check code

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup CI
        uses: ./.github/actions/ci-setup
      - name: Lint check
        run: make check lint
      - name: Imports check
        run: make check imports
      - name: Type check
        run: make check types
      - name: Format check
        run: make format

  test:
    name: Test

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: identity_user
          POSTGRES_PASSWORD: identity_password
          POSTGRES_DB: identity_db
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 10
        ports:
          - 5432:5432

    env:
      TEST_DATABASE_URL: postgresql://identity_user:identity_password@localhost:5432/identity_db

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup CI
        uses: ./.github/actions/ci-setup
      - name: Test suite
        run: make test

  audit:
    name: Security Audit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup CI
        uses: ./.github/actions/ci-setup
      - name: Install gitleaks (via action)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Security check
        run: make check-security
